// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.tripcost.lite

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PlatformApisPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class OcrRecognitionMode(val raw: Int) {
  FAST(0),
  ACCURATE(1);

  companion object {
    fun ofRaw(raw: Int): OcrRecognitionMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CloudAccountState(val raw: Int) {
  AVAILABLE(0),
  NO_ACCOUNT(1),
  RESTRICTED(2),
  COULD_NOT_DETERMINE(3);

  companion object {
    fun ofRaw(raw: Int): CloudAccountState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrRequest (
  val contractVersion: Long,
  val imagePath: String,
  val mode: OcrRecognitionMode,
  val preferredLanguages: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OcrRequest {
      val contractVersion = pigeonVar_list[0] as Long
      val imagePath = pigeonVar_list[1] as String
      val mode = pigeonVar_list[2] as OcrRecognitionMode
      val preferredLanguages = pigeonVar_list[3] as List<String>
      return OcrRequest(contractVersion, imagePath, mode, preferredLanguages)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      imagePath,
      mode,
      preferredLanguages,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OcrRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApisPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrCandidate (
  val text: String,
  val confidence: Double,
  val x: Double,
  val y: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OcrCandidate {
      val text = pigeonVar_list[0] as String
      val confidence = pigeonVar_list[1] as Double
      val x = pigeonVar_list[2] as Double
      val y = pigeonVar_list[3] as Double
      val width = pigeonVar_list[4] as Double
      val height = pigeonVar_list[5] as Double
      return OcrCandidate(text, confidence, x, y, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      confidence,
      x,
      y,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OcrCandidate) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApisPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrResult (
  val contractVersion: Long,
  val candidates: List<OcrCandidate>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OcrResult {
      val contractVersion = pigeonVar_list[0] as Long
      val candidates = pigeonVar_list[1] as List<OcrCandidate>
      return OcrResult(contractVersion, candidates)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      candidates,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OcrResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApisPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyncRecord (
  val contractVersion: Long,
  val id: String,
  val recordType: String,
  val schemaVersion: Long,
  val deviceId: String,
  val changeId: String,
  val payloadJson: String,
  val modifiedAtUtc: String,
  val deleted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncRecord {
      val contractVersion = pigeonVar_list[0] as Long
      val id = pigeonVar_list[1] as String
      val recordType = pigeonVar_list[2] as String
      val schemaVersion = pigeonVar_list[3] as Long
      val deviceId = pigeonVar_list[4] as String
      val changeId = pigeonVar_list[5] as String
      val payloadJson = pigeonVar_list[6] as String
      val modifiedAtUtc = pigeonVar_list[7] as String
      val deleted = pigeonVar_list[8] as Boolean
      return SyncRecord(contractVersion, id, recordType, schemaVersion, deviceId, changeId, payloadJson, modifiedAtUtc, deleted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      id,
      recordType,
      schemaVersion,
      deviceId,
      changeId,
      payloadJson,
      modifiedAtUtc,
      deleted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SyncRecord) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApisPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyncPushResult (
  val contractVersion: Long,
  val acceptedRecordIds: List<String>,
  val cursor: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncPushResult {
      val contractVersion = pigeonVar_list[0] as Long
      val acceptedRecordIds = pigeonVar_list[1] as List<String>
      val cursor = pigeonVar_list[2] as String?
      return SyncPushResult(contractVersion, acceptedRecordIds, cursor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      acceptedRecordIds,
      cursor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SyncPushResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApisPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyncPullResult (
  val contractVersion: Long,
  val records: List<SyncRecord>,
  val cursor: String? = null,
  val hasMore: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncPullResult {
      val contractVersion = pigeonVar_list[0] as Long
      val records = pigeonVar_list[1] as List<SyncRecord>
      val cursor = pigeonVar_list[2] as String?
      val hasMore = pigeonVar_list[3] as Boolean
      return SyncPullResult(contractVersion, records, cursor, hasMore)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      records,
      cursor,
      hasMore,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SyncPullResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApisPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SharedSnapshot (
  val contractVersion: Long,
  val payloadJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SharedSnapshot {
      val contractVersion = pigeonVar_list[0] as Long
      val payloadJson = pigeonVar_list[1] as String
      return SharedSnapshot(contractVersion, payloadJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contractVersion,
      payloadJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SharedSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApisPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PlatformApisPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OcrRecognitionMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CloudAccountState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OcrRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OcrCandidate.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OcrResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncRecord.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncPushResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncPullResult.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SharedSnapshot.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OcrRecognitionMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CloudAccountState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is OcrRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is OcrCandidate -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is OcrResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SyncRecord -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is SyncPushResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is SyncPullResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is SharedSnapshot -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VisionOcrApi {
  fun recognizeImage(request: OcrRequest, callback: (Result<OcrResult>) -> Unit)
  fun supportedRecognitionLanguages(): List<String>

  companion object {
    /** The codec used by VisionOcrApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApisPigeonCodec()
    }
    /** Sets up an instance of `VisionOcrApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VisionOcrApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trip_cost.VisionOcrApi.recognizeImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as OcrRequest
            api.recognizeImage(requestArg) { result: Result<OcrResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformApisPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PlatformApisPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trip_cost.VisionOcrApi.supportedRecognitionLanguages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.supportedRecognitionLanguages())
            } catch (exception: Throwable) {
              PlatformApisPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CloudSyncApi {
  fun accountStatus(callback: (Result<CloudAccountState>) -> Unit)
  fun pushChanges(records: List<SyncRecord>, cursor: String?, callback: (Result<SyncPushResult>) -> Unit)
  fun pullChanges(cursor: String?, callback: (Result<SyncPullResult>) -> Unit)

  companion object {
    /** The codec used by CloudSyncApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApisPigeonCodec()
    }
    /** Sets up an instance of `CloudSyncApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CloudSyncApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trip_cost.CloudSyncApi.accountStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.accountStatus{ result: Result<CloudAccountState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformApisPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PlatformApisPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trip_cost.CloudSyncApi.pushChanges$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordsArg = args[0] as List<SyncRecord>
            val cursorArg = args[1] as String?
            api.pushChanges(recordsArg, cursorArg) { result: Result<SyncPushResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformApisPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PlatformApisPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trip_cost.CloudSyncApi.pullChanges$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cursorArg = args[0] as String?
            api.pullChanges(cursorArg) { result: Result<SyncPullResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformApisPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PlatformApisPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SharedSnapshotApi {
  fun writeWidgetSnapshot(snapshot: SharedSnapshot, callback: (Result<Unit>) -> Unit)
  fun clearWidgetSnapshot(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by SharedSnapshotApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApisPigeonCodec()
    }
    /** Sets up an instance of `SharedSnapshotApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SharedSnapshotApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trip_cost.SharedSnapshotApi.writeWidgetSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val snapshotArg = args[0] as SharedSnapshot
            api.writeWidgetSnapshot(snapshotArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformApisPigeonUtils.wrapError(error))
              } else {
                reply.reply(PlatformApisPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trip_cost.SharedSnapshotApi.clearWidgetSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearWidgetSnapshot{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformApisPigeonUtils.wrapError(error))
              } else {
                reply.reply(PlatformApisPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WidgetControlApi {
  fun reloadTimelines()

  companion object {
    /** The codec used by WidgetControlApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApisPigeonCodec()
    }
    /** Sets up an instance of `WidgetControlApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WidgetControlApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.trip_cost.WidgetControlApi.reloadTimelines$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.reloadTimelines()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApisPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
